# Configuration file for wpa_supplicant
#
# IMPORTANT:
# Replace "Your_SSID" with your Wi-Fi network name.
# Replace "Your_Password" with your Wi-Fi password.

ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=staff
update_config=1
country=US

network={
    ssid="Heninger2.4G"
    psk="!qa2wS@9"
}
